#!/usr/bin/env python3

import subprocess

# tmux send-keys -t my_session "stop" ENTER
subprocess.run(['tmux', 'send-keys', '-t', 'server', 'stop', 'ENTER'])

# tmux wait my_session
subprocess.run(['tmux', 'wait', 'my_session'])

