from archlinux

run pacman -Syu jre-openjdk --noconfirm

run pacman -Syu vi vim git --noconfirm

run pacman -S zsh zsh-completions --noconfirm

run pacman -S maven --noconfirm

run export=/usr/lib/jvm/default
