from archlinux

run pacman -Syu jre-openjdk --noconfirm

run pacman -Syu vi vim git --noconfirm

run pacman -S zsh zsh-completions --noconfirm

run pacman -S maven --noconfirm

run pacman -S openssh --noconfirm

run pacman -S python --noconfirm

run pacman -S tmux --noconfirm

run pacman -S htop neofetch --noconfirm

run yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

run export PATH=$PATH:/workspaces/bukkit-plugin/.devcontainer/scripts/
